### ISSUE TITLE
Check in / Sign up

### ISSUE THREAD

**Issue by bethschechter** [maptime/Summit2015#10]
Shawn Goulet is going to own this task. We just need to make sure to print the list. Also could potentially take Squarecash / cash for people who want to enter.

Also need a stamp!!! or special sticker! @lyzidiamond any suggestions?

**Comment by lyzidiamond** [comment]
Rainbow stickers..... ON YOUR FACE

No but seriously I can probably steal a stamp from Molly.

**Comment by bethschechter** [comment]
I could have Dallas fabricate a rainbow branding iron. But i like the steal
a stamp fron Molly idea better :)

//typed with thumbs

**Comment by camilleanne** [comment]
do we have a rainbow stamp pad? otherwise I will procure one. because double rainbow: http://www.amazon.com/YazyCraft-Rainbow-Stamp-pad-Palette/dp/B00G2V65SM/ref=sr_1_2?s=toys-and-games&ie=UTF8&qid=1432771361&sr=1-2&keywords=rainbow+stamp+pad

**Comment by bethschechter** [comment]
uh yes please get that @camilleanne! I should be able to reimburse folks
for this too :)
