### ISSUE TITLE
Streaming / Skype / Hangout

### ISSUE THREAD

**Issue by bethschechter** [maptime/Summit2015#12]
Need help figuring this out.

**Comment by almccon** [comment]
I guess if we do a hangout on air, it will automatically save a recording. But how long can those things run? Maybe we'd need to restart at each session break?

We could also try something like the periscope app (periscope.tv) which just needs a phone. And it apparently records afterward...

**Comment by bethschechter** [comment]
I think that what we should do is do a hangout for each of the Unconference sessions. I've pinged @bertspaan directly to see if he can help - he said he would be extra hands that day :)

**Comment by bethschechter** [comment]
@almccon I'm down to use Periscope or whatever works!

**Comment by almccon** [comment]
doing a hangout on air.
