### ISSUE TITLE
Supplies!

### ISSUE THREAD

**Issue by bethschechter** [maptime/Summit2015#13]
There is a lot that I have that we can bring, and there are a few things we need to get. 

HAVE
Painter's tape
Some markers (thin tip)
Sticky notes (for unconference / breakout sessions)

BORROW
Stamp

NEED
Crayola markers (for decorating the map)
Rainbow stickers
Kind Bars

What else?

Mapzen / Alyssa is going to help us with a small order of office supplies and some basic snacks (kind bars, etc.). What else do we need?

@almccon @lyzidiamond @camilleanne what do you think?

**Comment by camilleanne** [comment]
bought that rainbow stamp pad: https://github.com/maptime/summit-2015/issues/10#issuecomment-106116201

I think it would also be a good idea to have a stack of legal pads or scratch paper -- is that something Mapzen could help us with?

**Comment by bethschechter** [comment]
Yes they can! No problemo.

Another thing to add to supply list: large piece of paper to list
unconference ideas.

//typed with thumbs

**Comment by bethschechter** [comment]
submitting to Mapzen now

**Comment by bethschechter** [comment]
the order has shipped! should be in Friday.

The rainbow stickers might not make it in time. @lyzidiamond @camilleanne if you find yourself by a Walgreens in NYC, do you think you can get some??

We won't like explode w/o rainbow stickers but we'd explode in a good way with them :)

**Comment by almccon** [comment]
I've got two sheets of :rainbow: stickers

**Comment by lyzidiamond** [comment]
I have like eight sheets.

**Comment by bethschechter** [comment]
COOOOOOOOOOL
ok we're good.

....can I have a sheet?

**Comment by bethschechter** [comment]
Supplies should have arrived at Mapzen today. Sent an email to Alyssa asking what the best plan for pickup / handoff is.

**Comment by lyzidiamond** [comment]
@bethschechter we are going to grab Monday morning from Mapzen. Dan from Mapzen has the box. He is there at 8:30 at the latest every day.

**Comment by bethschechter** [comment]
Awesome @ lyzidiamond! Thanks

//typed with thumbs

**Comment by bethschechter** [comment]
@lyzidiamond is picking these up day-of. We're good.
