### ISSUE TITLE
Revise schedule for 9-5

### ISSUE THREAD

**Issue by bethschechter** [maptime/Summit2015#17]
Per Alex Barth, we need to revise our schedule. The earliest we can be in is 8:45, and the latest we can be there is 5. With this in mind, I put this together:
### Maptime Summit Revised Schedule

8:45  volunteer arrival + set up

9:30        Breakfast & Gathering
10:00       Welcoming Announcements
10:15       Chapter Lightning Talks
11:00       BREAK
11:15       Unconference Session 1
12:00       LUNCH! // Pizza provided by Carto DB
1:30        Tutorial / Educational Development Training / Unconference Session 2
2:15        Github for Maptime Organizers / Unconference Session 3
3:00                BREAK
3:15        Logistics Q+A w/ HQ / Unconference Session 4
4:00        Closing remarks! Big map! Group photo!

4:30 Clean up! 

6:30 Karaoke party at Mapzen! 
Samsung Accelerator; 30 West 26th St 7th Floor, New York NY 10010

Does this work @lyzidiamond @almccon @camilleanne??

**Comment by almccon** [comment]
Looks reasonable, but I don't remember what the old schedule looked like.

**Comment by bethschechter** [comment]
Basically the same. The only diffs are that now
1. The Tutorial section is only 45 min
2. Every section of content also has an unconference section
3. I cut time for lightning talks to 45 min

It's tight. But doable :)

//typed with thumbs

**Comment by bethschechter** [comment]
I should also remove breakfast as there is no food in the room. But
gathering. Yes!

//typed with thumbs

**Comment by bethschechter** [comment]
Maptime: The Gathering

//typed with thumbs

**Comment by bethschechter** [comment]
final schedule posted, emailed

9:30        Sign-in
10:00       Welcoming Announcements (Beth)
10:30       Chapter Lightning Talks (Lyzi lead)
11:15       BREAK
11:30       Unconference Session 1
12:15       Group photo
12:30       LUNCH! // Pizza provided by Carto DB
1:30        Tutorial / Educational Development Training (Lyzi)
2:15        Unconference Session 2
3:00                BREAK
3:15        Logistics Q+A w/ HQ / Github for Maptime Organizers (All)
4:00        Closing remarks! Big map! Hugs (All)
