### ISSUE TITLE
create large non-mercator map for everyone to sign

### ISSUE THREAD

**Issue by bethschechter** [maptime/Summit2015#8]
with @camilleanne :)
I think a great big B+W would be amazing!
I can bring markers, stickers, all the things.

**Comment by camilleanne** [comment]
I'm about done with this -- used the Robinson projection since it was relatively easy. Will have something to print tonight or tomorrow.

**Comment by bethschechter** [comment]
Awesome! Do you want to lay it out with Maptime logo + thank you to Mapbox
on there somewhere?

Also how does Mapbox want to pay for printing this and the Maptime banner?
Is it easiest to put it on a Mapbox card? Or submit an invoice?

**Comment by lyzidiamond** [comment]
YES Robinson is my favorite.

**Comment by camilleanne** [comment]
A grey/bw version is here -- just need to stitch together for printing: https://api.tiles.mapbox.com/v4/camilleanne.5020818e/page.html?access_token=pk.eyJ1IjoiY2FtaWxsZWFubmUiLCJhIjoiN0pleXVXTSJ9.olk86fBWmW6kFpmyFfTDqw#4/50.85/15.29

**Comment by almccon** [comment]
very slick!

**Comment by bethschechter** [comment]
Oh man! I want to see this but my phone won't let me. Can't wait to see!

**Comment by camilleanne** [comment]
So -- printing. I made it grey scale for easy marking, but where do we think we want to get it printed? photojojo's [engineer prints](photojojo.com/engineerprints/) are fun, but perhaps a bit unpredictable.

And dimensions...

**Comment by bethschechter** [comment]
I love ArcBryant. They are fast and cheap...even if we want to add our
rainbow logo :)

We also need to print the Maptime banner. We could send it to the same
place.

**Comment by camilleanne** [comment]
@bethschechter https://www.dropbox.com/work/Maptime%20Maps

there's zoom 4 in there (no city labels) and zoom 6 (with city labels) I was going to do some test prints of just a bit of them on my home printer to see if the city labels would be a reasonable size at all, but I didn't get to. They're both like 100in x 50in @ 300dpi in png. Unfortunately we can't export svgs of maps yet, but you should be able to open these in illustrator.

**Comment by bethschechter** [comment]
This is fucking awesome. Thank you so so so much!!

//typed with thumbs

**Comment by bethschechter** [comment]
@camilleanne hey girl hey, I can't access that file...keep getting redirected to Dropbox Business, and then I don't see it listed in my folders, shared folders, etc. Can you upload it to the Maptime Google Docs folder?

I'm going to get tattoo finished today but will be back online this eve. Also working all day tomorrow. So no rush.

Thank you!

**Comment by camilleanne** [comment]
@bethschechter did some test prints at home and I'm pretty happy with zoom 6 -- city names look good. Also did some updating to where country names were placed, so we should use this file going forward: https://www.dropbox.com/s/cempjlyz53lk5i0/Maptime%20-%20Robinson%20Projection-z6-2.png?dl=0

I've updated the permissions so you can see it, but I'll add it to the google docs folder too.

**Comment by bethschechter** [comment]
copy this @camilleanne! Thank you.
I haven't heard back from Arc yet; will hopefully get something from them
soon.

**Comment by bethschechter** [comment]
@camilleanne just looked at the file - looks AMAZING! One thing I'm wondering: all the gray that is the ocean may come out striated on a large-scale plotter. Do you think we could have just the outline of the earth and not the gray?

Today I will be cleaning the shop (long stupid story) but will be able to do this tomorrow. I'll be hiding out at my dad's house in ATL this week and knocking things off the to-do list. 

xoxoxoxo

**Comment by camilleanne** [comment]
I was wondering about the grey too -- I'll update the image.

**Comment by bethschechter** [comment]
Great! Thank you.
So exciting!

//typed with thumbs

**Comment by camilleanne** [comment]
Uploading a much lighter version with no big blocks of grey into the maptime google drive right now.

**Comment by camilleanne** [comment]
Map sent to printer!

**Comment by bethschechter** [comment]
Right i should add updates here. Got it!

//typed with thumbs

**Comment by bethschechter** [comment]
printed and shipped
